// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSB0AAIg78tfJHCfD-WFdA9yYyDZxBRVQ',
    appId: '1:345851419457:web:2ff96a4a36b2b9ee80dfc0',
    messagingSenderId: '345851419457',
    projectId: 'flutterchat-be819',
    authDomain: 'flutterchat-be819.firebaseapp.com',
    storageBucket: 'flutterchat-be819.appspot.com',
    measurementId: 'G-K05BK1HS2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk60b0IhEHW5e8AEJ_eilsRay2tCvY10I',
    appId: '1:345851419457:android:f7783833c4bc02f980dfc0',
    messagingSenderId: '345851419457',
    projectId: 'flutterchat-be819',
    storageBucket: 'flutterchat-be819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfjjP-U7TiI7Xz_7zUXSipeIPGiUT39HY',
    appId: '1:345851419457:ios:d977b9e1fcfed5bc80dfc0',
    messagingSenderId: '345851419457',
    projectId: 'flutterchat-be819',
    storageBucket: 'flutterchat-be819.appspot.com',
    iosBundleId: 'com.example.flutterchat',
  );
}
